name: Chomp API CMake Build

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    # Matrix build for MacOS and Windows only
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Install dependencies on MacOS
    - name: Install dependencies (MacOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install cmake

    # Configure CMake
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    # Build
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # Test (optional, if you have CTest configured)
    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
